//! Apache Iceberg table reader: spec-compliant metadata, Avro manifests,
//! Parquet data files.
//!
//! # What an Iceberg table IS, to this engine
//!
//! A metadata layer over Parquet. Reading one means:
//!
//! 1. find the CURRENT `metadata/*.metadata.json` (or the one a requested
//!    snapshot lives in),
//! 2. pick a snapshot (current by default, or by id for time travel),
//! 3. read its manifest LIST (Avro), which names the manifest FILES,
//! 4. read each manifest file (Avro), which names the data files with their
//!    per-entry status (added / existing / deleted),
//! 5. hand the surviving Parquet paths to the ordinary [`ParquetTable`].
//!
//! The result IS a `ParquetTable`, so everything built on Parquet — morsel
//! scans, footer statistics, row-group pruning, and crucially the
//! distributed layer's split enumeration (`parquet_files()`) — works on
//! Iceberg tables with no further changes. Sharding an Iceberg table across
//! nodes is exactly sharding its manifest-listed files.
//!
//! # What is refused, loudly
//!
//! * **Delete files** (v2 row-level deletes, position or equality): a reader
//!   that ignores them returns rows the table says are gone. Refused by name.
//! * **Non-Parquet data files** (Avro/ORC data): refused by name.
//! * **Empty tables**: a table whose snapshot lists no data files cannot
//!   currently provide a schema through the Parquet path. Refused with the
//!   snapshot id rather than answering zero rows against a guessed schema.
//!
//! # Layout facts this was written against (verified, not assumed)
//!
//! Fixtures generated by pyiceberg 0.11 `SqlCatalog` (`scripts/iceberg_gen.py`,
//! `data/tpch-*-iceberg/`): format-version 2; `metadata/NNNNN-<uuid>.metadata.json`
//! with NO `version-hint.text`; manifest lists `snap-<id>-*.avro` (record
//! `manifest_file`, deflate); manifest files `<uuid>-m0.avro` (record
//! `manifest_entry` with `status` + nested `data_file`, deflate); absolute
//! `file://` URIs throughout. Tables written by Spark's HadoopCatalog use
//! `vN.metadata.json` + `version-hint.text` instead — both discovery rules are
//! implemented and tested.

use crate::error::{QueryError, Result};
use crate::storage::parquet::ParquetTable;
use serde::Deserialize;
use std::path::{Path, PathBuf};

/// One snapshot of an Iceberg table, as this reader needs it.
#[derive(Debug, Clone, Deserialize)]
pub struct Snapshot {
    #[serde(rename = "snapshot-id")]
    pub snapshot_id: i64,
    #[serde(rename = "timestamp-ms")]
    pub timestamp_ms: i64,
    #[serde(rename = "manifest-list")]
    pub manifest_list: String,
    #[serde(default)]
    pub summary: serde_json::Value,
}

/// The slice of `*.metadata.json` this reader uses.
#[derive(Debug, Deserialize)]
struct TableMetadata {
    #[serde(rename = "format-version")]
    format_version: u32,
    #[serde(rename = "current-snapshot-id", default)]
    current_snapshot_id: Option<i64>,
    #[serde(default)]
    snapshots: Vec<Snapshot>,
    #[serde(rename = "last-updated-ms", default)]
    last_updated_ms: i64,
}

/// An opened Iceberg table: the resolved file set plus how it was resolved.
pub struct IcebergTable {
    /// The provider every query path actually uses.
    pub table: ParquetTable,
    /// Snapshot the file set came from.
    pub snapshot_id: i64,
    /// Every snapshot the metadata lists, oldest first — for `.iceberg-versions`.
    pub snapshots: Vec<Snapshot>,
    /// The metadata file the resolution used.
    pub metadata_path: PathBuf,
}

/// Open an Iceberg table directory, optionally at a specific snapshot.
pub fn open_table(dir: impl AsRef<Path>, snapshot_id: Option<i64>) -> Result<IcebergTable> {
    let dir = dir.as_ref();
    let metadata_path = latest_metadata_file(dir)?;
    let text = std::fs::read_to_string(&metadata_path)
        .map_err(|e| QueryError::Storage(format!("read {}: {e}", metadata_path.display())))?;
    let meta: TableMetadata = serde_json::from_str(&text)
        .map_err(|e| QueryError::Storage(format!("parse {}: {e}", metadata_path.display())))?;
    if meta.format_version != 1 && meta.format_version != 2 {
        return Err(QueryError::Storage(format!(
            "{}: Iceberg format-version {} is not supported (1 and 2 are)",
            metadata_path.display(),
            meta.format_version
        )));
    }

    let mut snapshots = meta.snapshots.clone();
    snapshots.sort_by_key(|s| s.timestamp_ms);

    let chosen = match snapshot_id {
        Some(id) => snapshots
            .iter()
            .find(|s| s.snapshot_id == id)
            .ok_or_else(|| {
                QueryError::Storage(format!(
                    "snapshot {id} does not exist in {}; available: [{}]",
                    metadata_path.display(),
                    snapshots
                        .iter()
                        .map(|s| s.snapshot_id.to_string())
                        .collect::<Vec<_>>()
                        .join(", ")
                ))
            })?,
        None => {
            let current = meta.current_snapshot_id.ok_or_else(|| {
                QueryError::Storage(format!(
                    "{} has no current snapshot; the table has never been written to",
                    metadata_path.display()
                ))
            })?;
            snapshots
                .iter()
                .find(|s| s.snapshot_id == current)
                .ok_or_else(|| {
                    QueryError::Storage(format!(
                        "current-snapshot-id {current} is not in the snapshot list of {}",
                        metadata_path.display()
                    ))
                })?
        }
    };

    let manifest_list = resolve_uri(&chosen.manifest_list, dir)?;
    let files = data_files_of(&manifest_list, dir)?;
    if files.is_empty() {
        return Err(QueryError::Storage(format!(
            "snapshot {} of {} lists no data files; refusing to serve an empty table \
             against a guessed schema",
            chosen.snapshot_id,
            dir.display()
        )));
    }

    let table = ParquetTable::try_from_files(files)?;
    Ok(IcebergTable {
        table,
        snapshot_id: chosen.snapshot_id,
        snapshots,
        metadata_path,
    })
}

/// The table's current `*.metadata.json`, by the two discovery rules that
/// exist in the wild:
///
/// * `version-hint.text` (HadoopCatalog): contains N or `vN`; the file is
///   `vN.metadata.json`.
/// * otherwise every `*.metadata.json` is read and the one with the greatest
///   `last-updated-ms` wins (ties broken by filename, so equal-timestamp
///   metadata written in one millisecond still resolves deterministically).
///   Filename prefixes (`00002-...`) are NOT trusted as the ordering: they
///   are a pyiceberg convention, not part of the spec.
fn latest_metadata_file(dir: &Path) -> Result<PathBuf> {
    let mdir = dir.join("metadata");
    let hint = mdir.join("version-hint.text");
    if hint.is_file() {
        let v = std::fs::read_to_string(&hint)
            .map_err(|e| QueryError::Storage(format!("read {}: {e}", hint.display())))?;
        let v = v.trim().trim_start_matches('v');
        let candidate = mdir.join(format!("v{v}.metadata.json"));
        if !candidate.is_file() {
            return Err(QueryError::Storage(format!(
                "version-hint.text says {v}, but {} does not exist",
                candidate.display()
            )));
        }
        return Ok(candidate);
    }

    let mut best: Option<(i64, PathBuf)> = None;
    let entries = std::fs::read_dir(&mdir).map_err(|e| {
        QueryError::Storage(format!(
            "{} is not an Iceberg table (no metadata/ directory): {e}",
            dir.display()
        ))
    })?;
    for entry in entries {
        let path = entry
            .map_err(|e| QueryError::Storage(format!("list {}: {e}", mdir.display())))?
            .path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if !name.ends_with(".metadata.json") {
            continue;
        }
        let text = std::fs::read_to_string(&path)
            .map_err(|e| QueryError::Storage(format!("read {}: {e}", path.display())))?;
        let meta: TableMetadata = serde_json::from_str(&text)
            .map_err(|e| QueryError::Storage(format!("parse {}: {e}", path.display())))?;
        let key = (meta.last_updated_ms, path.clone());
        match &best {
            None => best = Some(key),
            Some((t, p)) => {
                if (meta.last_updated_ms, &path) > (*t, p) {
                    best = Some(key);
                }
            }
        }
    }
    best.map(|(_, p)| p).ok_or_else(|| {
        QueryError::Storage(format!(
            "{}/metadata contains no *.metadata.json; not an Iceberg table",
            dir.display()
        ))
    })
}

/// Data files of a snapshot: manifest list -> manifest files -> live entries.
fn data_files_of(manifest_list: &Path, table_dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    for manifest_path in avro_records(manifest_list)?
        .into_iter()
        .map(|r| field_str(&r, "manifest_path", manifest_list))
        .collect::<Result<Vec<_>>>()?
    {
        let manifest = resolve_uri(&manifest_path, table_dir)?;
        for entry in avro_records(&manifest)? {
            // status: 0 = EXISTING, 1 = ADDED, 2 = DELETED. A deleted entry
            // is how a manifest says "this file is no longer in the table".
            let status = field_i32(&entry, "status", &manifest)?;
            if status == 2 {
                continue;
            }
            let data_file = match entry {
                apache_avro::types::Value::Record(fields) => fields
                    .into_iter()
                    .find(|(n, _)| n == "data_file")
                    .map(|(_, v)| unwrap_union(v))
                    .ok_or_else(|| {
                        QueryError::Storage(format!(
                            "{}: manifest_entry has no data_file field",
                            manifest.display()
                        ))
                    })?,
                other => {
                    return Err(QueryError::Storage(format!(
                        "{}: expected manifest_entry record, got {:?}",
                        manifest.display(),
                        kind_of(&other)
                    )))
                }
            };

            // content: 0 = data, 1 = position deletes, 2 = equality deletes.
            // Serving a table while ignoring its delete files would return
            // deleted rows as if they existed.
            let content = field_i32(&data_file, "content", &manifest).unwrap_or(0);
            if content != 0 {
                return Err(QueryError::NotImplemented(format!(
                    "{} contains Iceberg delete files (content={content}); row-level \
                     deletes are not supported — compact the table first",
                    manifest.display()
                )));
            }

            let format = field_str(&data_file, "file_format", &manifest)?;
            if !format.eq_ignore_ascii_case("parquet") {
                return Err(QueryError::NotImplemented(format!(
                    "{}: data file format {format} is not supported (PARQUET is)",
                    manifest.display()
                )));
            }
            files.push(resolve_uri(
                &field_str(&data_file, "file_path", &manifest)?,
                table_dir,
            )?);
        }
    }
    files.sort();
    files.dedup();
    Ok(files)
}

/// Every record of an Avro object-container file.
fn avro_records(path: &Path) -> Result<Vec<apache_avro::types::Value>> {
    let file = std::fs::File::open(path)
        .map_err(|e| QueryError::Storage(format!("open {}: {e}", path.display())))?;
    let reader = apache_avro::Reader::new(std::io::BufReader::new(file))
        .map_err(|e| QueryError::Storage(format!("avro {}: {e}", path.display())))?;
    reader
        .map(|r| {
            r.map(unwrap_union)
                .map_err(|e| QueryError::Storage(format!("avro {}: {e}", path.display())))
        })
        .collect()
}

/// Avro unions (nullable fields) wrap their value; strip that.
fn unwrap_union(v: apache_avro::types::Value) -> apache_avro::types::Value {
    match v {
        apache_avro::types::Value::Union(_, inner) => unwrap_union(*inner),
        other => other,
    }
}

fn kind_of(v: &apache_avro::types::Value) -> &'static str {
    use apache_avro::types::Value as V;
    match v {
        V::Record(_) => "record",
        V::Null => "null",
        V::String(_) => "string",
        _ => "other",
    }
}

fn field_of(
    record: &apache_avro::types::Value,
    name: &str,
    from: &Path,
) -> Result<apache_avro::types::Value> {
    match record {
        apache_avro::types::Value::Record(fields) => fields
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, v)| unwrap_union(v.clone()))
            .ok_or_else(|| {
                QueryError::Storage(format!("{}: record has no `{name}` field", from.display()))
            }),
        other => Err(QueryError::Storage(format!(
            "{}: expected a record with `{name}`, got {}",
            from.display(),
            kind_of(other)
        ))),
    }
}

fn field_str(record: &apache_avro::types::Value, name: &str, from: &Path) -> Result<String> {
    match field_of(record, name, from)? {
        apache_avro::types::Value::String(s) => Ok(s),
        other => Err(QueryError::Storage(format!(
            "{}: `{name}` is {} rather than a string",
            from.display(),
            kind_of(&other)
        ))),
    }
}

fn field_i32(record: &apache_avro::types::Value, name: &str, from: &Path) -> Result<i32> {
    match field_of(record, name, from)? {
        apache_avro::types::Value::Int(i) => Ok(i),
        apache_avro::types::Value::Long(l) => Ok(l as i32),
        other => Err(QueryError::Storage(format!(
            "{}: `{name}` is {} rather than an int",
            from.display(),
            kind_of(&other)
        ))),
    }
}

/// Turn a metadata URI into a local path.
///
/// Accepts `file:///abs`, `file:/abs` (Gravitino-style normalization), plain
/// absolute paths, and paths relative to the table directory. Anything with a
/// non-file scheme (s3://, hdfs://) is refused by name — pretending a remote
/// URI is local would "work" until it reads someone else's file.
fn resolve_uri(uri: &str, table_dir: &Path) -> Result<PathBuf> {
    if let Some(rest) = uri.strip_prefix("file:") {
        let path = rest.trim_start_matches("//");
        let path = if path.starts_with('/') {
            path.to_string()
        } else {
            format!("/{path}")
        };
        return Ok(PathBuf::from(path));
    }
    if uri.contains("://") {
        return Err(QueryError::NotImplemented(format!(
            "Iceberg metadata points at `{uri}`; only file:// and local paths are supported"
        )));
    }
    let p = PathBuf::from(uri);
    if p.is_absolute() {
        Ok(p)
    } else {
        Ok(table_dir.join(p))
    }
}

/// Does `dir` look like an Iceberg table? (Used by `--tables` auto-detection.)
pub fn is_iceberg_dir(dir: &Path) -> bool {
    let mdir = dir.join("metadata");
    mdir.is_dir()
        && std::fs::read_dir(&mdir)
            .map(|mut it| {
                it.any(|e| {
                    e.ok()
                        .map(|e| {
                            e.file_name()
                                .to_str()
                                .map(|n| n.ends_with(".metadata.json"))
                                .unwrap_or(false)
                        })
                        .unwrap_or(false)
                })
            })
            .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physical::operators::TableProvider;

    fn fixture(table: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!("data/tpch-1mb-iceberg/{table}"))
    }

    #[test]
    fn resolve_uri_accepts_the_forms_that_exist_in_the_wild() {
        let dir = Path::new("/tbl");
        for (uri, want) in [
            ("file:///a/b.parquet", "/a/b.parquet"),
            ("file:/a/b.parquet", "/a/b.parquet"),
            ("/a/b.parquet", "/a/b.parquet"),
            ("data/b.parquet", "/tbl/data/b.parquet"),
        ] {
            assert_eq!(resolve_uri(uri, dir).unwrap(), PathBuf::from(want), "{uri}");
        }
        let err = resolve_uri("s3://bucket/k", dir).unwrap_err();
        assert!(matches!(err, QueryError::NotImplemented(_)), "{err:?}");
    }

    #[test]
    fn opens_a_pyiceberg_table_and_counts_its_files() {
        let t = open_table(fixture("lineitem"), None).expect("open lineitem");
        assert!(!t.table.parquet_files().unwrap().is_empty());
        assert_eq!(t.snapshots.len(), 1);
    }

    #[test]
    fn the_multi_snapshot_table_resolves_both_ways() {
        // orders in the 1mb fixture has 2 snapshots: 1500 rows, then +100.
        let current = open_table(fixture("orders"), None).expect("open orders");
        assert_eq!(current.snapshots.len(), 2);
        let first_id = current.snapshots[0].snapshot_id;
        assert_ne!(first_id, current.snapshot_id, "current must be the SECOND");

        let old = open_table(fixture("orders"), Some(first_id)).expect("time travel");
        assert_eq!(old.snapshot_id, first_id);
        // The first snapshot has strictly fewer data files resolved.
        assert!(
            old.table.parquet_files().unwrap().len() < current.table.parquet_files().unwrap().len(),
            "older snapshot must not include the second append's file"
        );
    }

    #[test]
    fn a_missing_snapshot_is_an_error_listing_what_exists() {
        let msg = match open_table(fixture("orders"), Some(42)) {
            Err(e) => e.to_string(),
            Ok(_) => panic!("snapshot 42 must not resolve"),
        };
        assert!(msg.contains("snapshot 42"), "{msg}");
        assert!(msg.contains("available"), "{msg}");
    }

    #[test]
    fn a_non_iceberg_dir_is_refused_with_the_reason() {
        let msg = match open_table(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/tpch-1mb"),
            None,
        ) {
            Err(e) => e.to_string(),
            Ok(_) => panic!("a plain parquet dir must not open as Iceberg"),
        };
        assert!(msg.contains("metadata"), "{msg}");
    }

    #[test]
    fn is_iceberg_dir_detects_tables_and_rejects_parquet_dirs() {
        assert!(is_iceberg_dir(&fixture("orders")));
        assert!(!is_iceberg_dir(
            &PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/tpch-1mb")
        ));
    }
}
